comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false  # Change to true for less noise
  require_base: true
  require_head: true

coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        informational: true
